### PR TITLE
Update Minecraft Wiki links to new domain after fork

### PR DESCRIPTION
**Pull request by misode**
The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: <https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom>. This PR updates all the URLs to the new domain: minecraft.wiki

### CODE REVIEW

**Comment by DerEchtePilz** [comment]
Please don't target the `master` branch, instead target the `dev/dev` branch with your pull request.

**Comment by DerEchtePilz** [comment]
That said, I am not sure if we want to update previous documentation as this project follows SemVer rules.
I would suggest leaving this as it is currently and I am getting back to you once I know more :D

**Comment by JorelAli** [comment]
Yes, @DerEchtePilz is precisely correct. In accordance to our Semantic Versioning rules, we shouldn't change any of the old documentation.

We're due to release 9.2.0 within the next ~30 hours, and this would be a great candidate for some lovely 9.2.0 documentation. I'll not accept any changes to files in `docs/`.

You've references to some old links that point to `minecraft.gamepedia.com`. Using a quick VSCode search yields a a lot of other links:

```
pattern: https?://.*minecraft.(gamepedia|fandom)
include: *.java,*.md
exclude: docs/
```

```yml
19 results - 17 files

commandapi-platforms\commandapi-bukkit\commandapi-bukkit-core\src\main\java\dev\jorel\commandapi\arguments\AdventureChatComponentArgument.java:
  39  	 * Constructs a ChatComponent argument with a given node name. Represents raw JSON text, used in Book MetaData, Chat and other various areas of Minecraft
  40: 	 * @see <a href="https://minecraft.gamepedia.com/Commands#Raw_JSON_text">Raw JSON text</a> 
  41  	 * @param nodeName the name of the node for argument

commandapi-platforms\commandapi-bukkit\commandapi-bukkit-core\src\main\java\dev\jorel\commandapi\arguments\ChatComponentArgument.java:
  42  	 * 
  43: 	 * @see <a href="https://minecraft.gamepedia.com/Commands#Raw_JSON_text">Raw
  44  	 *      JSON text</a>

commandapi-platforms\commandapi-bukkit\commandapi-bukkit-test\commandapi-bukkit-test-tests\src\test\java\dev\jorel\commandapi\test\arguments\ArgumentBlockStateTests.java:
  43  	
  44: 	// Block states can be looked up here: https://minecraft.fandom.com/wiki/Block_states
  45  

commandapi-platforms\commandapi-bukkit\commandapi-bukkit-test\commandapi-bukkit-test-tests\src\test\java\dev\jorel\commandapi\test\arguments\ArgumentItemStackTests.java:
  78  		
  79: 		// NBT examples from https://minecraft.fandom.com/wiki/Tutorials/Command_NBT_tags#Items
  80  		

commandapi-platforms\commandapi-bukkit\commandapi-bukkit-test\commandapi-bukkit-test-tests\src\test\java\dev\jorel\commandapi\test\arguments\ArgumentLocationTests.java:
   98  			
   99: 			// As defined in https://minecraft.fandom.com/wiki/Coordinates#Local_coordinates:
  100  			// For example, /tp ^ ^ ^5 teleports the player 5 blocks forward. If they turn

  206  			
  207: 			// As defined in https://minecraft.fandom.com/wiki/Coordinates#Local_coordinates:
  208  			// For example, /tp ^ ^ ^5 teleports the player 5 blocks forward. If they turn

docssrc\src\argument_blockpredicate.md:
  2  
  3: The `BlockPredicateArgument` is used to represent a "test" for Minecraft blocks. This can consist of tags, such as the ones listed [here on the MinecraftWiki](https://minecraft.gamepedia.com/Tag#Blocks), or individual blocks. If a block matches the tag or block, then the predicate is satisfied.
  4  

docssrc\src\argument_chat_adventure.md:
  52  
  53: The `AdventureChatComponentArgument` class accepts raw chat-based JSON as valid input, as declared [here](https://minecraft.gamepedia.com/Raw_JSON_text_format). This is converted into Adventure's `Component` class.
  54  

docssrc\src\argument_chat_spigot.md:
  47  
  48: The `ChatComponentArgument` class accepts raw chat-based JSON as valid input. Despite being regular JSON, it _must_ conform to the standard declared [here](https://minecraft.gamepedia.com/Raw_JSON_text_format), which consists of JSON that has a limited subset of specific keys (In other words, you can have a JSON object that has the key `text`, but not one that has the key `blah`).
  49  

docssrc\src\argument_chats.md:
  6  - **Chat**: Text which is said in chat. This also includes entity selectors such as `@a` and `@r`
  7: - **ChatComponent**: Minecraft's [Raw JSON text format](https://minecraft.gamepedia.com/Raw_JSON_text_format)
  8  

docssrc\src\argument_entities.md:
  6  
  7: Minecraft's [target selectors](https://minecraft.gamepedia.com/Commands#Target_selectors) (e.g. `@a` or `@e`) are implemented using the subclasses of the `EntitySelectorArgument` class. This allows you to select specific entities based on certain attributes.
  8  

docssrc\src\argument_itemstackpredicate.md:
  2  
  3: Similar to the `BlockPredicateArgument`, the `ItemStackPredicateArgument` is a way of performing predicate checks on `ItemStack` objects. These can represent tags, such as the ones declared [here on the MinecraftWiki](https://minecraft.gamepedia.com/Tag#Items), or individual items. The cast type for this argument is `Predicate<ItemStack>`.
  4  

docssrc\src\argument_namespacedkey.md:
  2  
  3: NamespacedKey arguments represent Minecraft's [resource locations](https://minecraft.fandom.com/wiki/Resource_location), or namespaced keys. This argument is casted to Bukkit's `NamespacedKey` object.
  4  

docssrc\src\argument_particle.md:
  21  
  22: The particle argument requires additional data for a particle depending on what the particle is. Information about this can be found [on the Argument types page on the MinecraftWiki](https://minecraft.fandom.com/wiki/Argument_types#particle). The following particles have additional data required to display them:
  23  

docssrc\src\argument_scoreboards.md:
  4  
  5: - The `ScoreHolderArgument` class represents **score holder** - a player's name or an entity's UUID that has scores in an objective. This is described in more detail [on the Minecraft Wiki](https://minecraft.gamepedia.com/Scoreboard#Objectives).
  6: - The `ScoreboardSlotArgument` class represents a **display slot** (sidebar, list or belowName) as well as the team color if the display is the sidebar. This is described in more detail [on the Minecraft Wiki](https://minecraft.gamepedia.com/Scoreboard#Display_slots).
  7  

docssrc\src\conversionentityselectors.md:
  2  
  3: [Entity selectors](https://minecraft.fandom.com/wiki/Target_selectors) (also known as target selectors) allows you to select certain entities or players which fit a certain criteria when writing a command. Typically, these are of the form `@p`, `@r`, `@a`, `@e` or `@s`. By default, when converting a command without arguments, the CommandAPI will not handle these entity selectors. In order to get entity selectors to cooperate with plugins, they must be declared in the relevant `config.yml` section.
  4  

docssrc\src\conversionforownerssingleargs.md:
  140  
  141: The list of types are based on [the list of argument types from the Minecraft Wiki](https://minecraft.gamepedia.com/Argument_types), with a few changes. The complete list that the CommandAPI supports is as follows:
  142  

docssrc\src\functions.md:
  2  
  3: The CommandAPI has support to use Minecraft's [functions](https://minecraft.gamepedia.com/Function_(Java_Edition)) within your plugins. This is handled by using a class provided by the CommandAPI called `FunctionWrapper`, which allows you to execute functions. The CommandAPI also provides support to let you run your own commands within Minecraft function files.
  4  
```

**Comment by misode** [comment]
Thanks for highlighting that issue. I believe the current commit should be correct.

**Pull request merged**
